### ISSUE TITLE
new value for judge.py

### ISSUE THREAD

**Issue by ghost** [shkey/killurp#1]
querystring = {
                "wjbm":c_info[0],
                "bpr":c_info[1],
                "pgnr":c_info[5],
                "0000000054":"10_1",
                "0000000055":"10_1",
                "0000000056":"5_1",
                "0000000057":"5_1",
                "0000000058":"5_1",
                "0000000059":"5_1",
                "0000000060":"5_1",
                "0000000061":"5_1",
                "0000000062":"5_1",
                "0000000063":"5_1",
                "0000000064":"6_1",
                "0000000065":"7_1",
                "0000000066":"6_1",
                "0000000067":"6_1",
                "0000000068":"5_1",
                "0000000069":"5_1",
                "0000000070":"5_1",
                "zgpj":get_random_word().encode('gb2312')
            }

**Comment by shkey** [comment]
OK，已更
